In [1]:
import tensorflow as tf


In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\vinay\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [3]:
print(tf.version.VERSION)

2.10.0


In [4]:
# It has vectors and does the matrix computation :  it does 2 , 3 ,  4 and sometiems 5 dimensions ( 4 dimentions for imgaes )
# vectors and Matrices and the tf does computation for the tensors 
# Each tensor has a data type and a shape  : they sometimes has flot string etc. 
# shape is the representaiton for the dimension for  the data.  



In [5]:
# Creating tensors : 
string  = tf.Variable("this is a string " , tf.string)
number  = tf.Variable(33 , tf.int16)
floating  = tf.Variable(3.567 , tf.float16)

# rank Degree of tensors:  



Another word for rank is the degree , These terms simple mean the number of dimensions involved in the tensor what we created above is a tensor of rank 0 also knows as scaler. 
For higher degree tensors we can define them as  : 


In [8]:
rank1_tensor  = tf.Variable(['Test_1'] , tf.string)
rank2_tensor  = tf.Variable(["Test" , "okay"] , ["Test" , "Yes"] , tf.string)

# now to check the rank of the tensor we can use the code as  : 
rank2_tensor.shape

TensorShape([2])

In [9]:
rank1_tensor.shape

TensorShape([1])

Make sure that there are same amount of tensors in the code while defining the tensors and they should be uniform. 

# Changing the shape of the tensors : 

Sometimes we have to change the shape of the tensors so that they match when there are differnet shape and flat it out to make it the same dimension / shape as other tensor or .......

In [10]:
tensor1 = tf.ones([1,2,3])

tensor_2 = tf.reshape(tensor1 , [2 ,3 ]) # reshape existing data from tensor 1 and then adding 2 and 3 in that one as well 

# we can use this method to reshape it again and again



# Types of tensors : 
1.variables 
2. Constant
3. Placeholder
4. Sparse Tensor 

apart from variable other are immutable  

To evaluate a tensor we need to make a session since tensors represent a partially complte computation we will sometimes need to run whats callsed a sssion to evaluate the tensor

In [11]:
with tf.Session() as sess:
    tensor.eval()   # tensor is the name of the tensro 

AttributeError: module 'tensorflow' has no attribute 'Session'

In [12]:
import tensorflow as tf

print(tf.version.VERSION)

2.10.0


In [13]:
t  = tf.zeros([5,5,5,5,5])
print(t)

tf.Tensor(
[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
   

## Core Learning Algorithms :  

1. Linear Regression
2. Classification
3. Clustering
4. Hidden Markov Models 



In [15]:
# Blunt Code for the linear regression using tensorflow :  

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from IPython.display import clear_output
import urllib

import tensorflow.compat.v2.feature_column as fc   # used for the tablular data for the feature columns

import tensorflow as tf



In [ ]:
# Specifically for the tabular data and linear regression  : 

dftrain  = pd.read_csv('data frame location ') # Training data 
dfeval  = pd.read_csv('data frame antoher testing dta set ') # Testing data

y_train  = dftrain.pop('Survived')
y_eval = dfeval.pop("Survived")  # This is the column name in the dummy data 

CATEGORICAL_COLUMNS  = ['']

NUMERICAL_COLUMNS  = ['']

feature_columns  =  []

for feature_name in CATEGORICAL_COLUMNS:
    vocabulary = dftrain[feature_name].unique() # Gets the list of all unique values from given feature column
    feature_columns.append(tf.feature_column.numeric_column(feature_name , dtype=tf.float32))

print(feature_columns)



In [1]:
dftrain[feature_name].unique()

NameError: name 'dftrain' is not defined

For small datset we can load the dataset in one go but if the dataset is large we need to laod the dataset in batches in the model and to make the batches : 

for example in this one we maek batches of 32 : 
epochs :  is the iterations ( how many times the model gonna see the same data  - this makes the model to learn about the datsaet but with each iteration the model sees the data but in other sequence )

Input Function :  


In [2]:
# Input FUnciton : way to define the data how the data is gonna be broken in epochs  : it takes the data and encodes it in tf.data.Dataset object : casue tensorflow requres the input in this form to ake  a model from it 


def make_input_fn(data_df , label_df , num_epoches  = 10 , shuffle  = True  , batch_size = 32):
    def input_function(): # THe innner function : 
        ds = tf.data.Dataset.from_tensor_slices((dict(data_df) , label_df))
        if shuffle:
            ds = ds.shuffle(1000) # Randomize order of data : 
            ds = ds.batch(batch_size).repeat(num_epoches) # Split dataset into batches of 32 and repeat process for number of epoches 
            return ds # Return a batch of the dataset : 
    return input_function # Retur a function object for use : 



train_input_fn  = make_input_fn(dftrain , y_train) # Here we will call the input function that was returned to us to get a 
eval_input_fn = make_input_fn(dfeval , y_eval , num_epoches=1 , shuffle=False)


linear_est = tf.estimator.LinearClassifier(feature_columns=feature_columns) # Train the model for linear classification  / Regression 
 
result  = linear_est.evaluate(eval_input_fn) # get model meterics / stats by testing on testing data.

Clear_output()  # Clears the console output 

print(result['accuracy']) # The result variable is simple a dict of stas about our model


NameError: name 'dftrain' is not defined

They are used to make large batches of data and not good to make predictions for only one set of data. 
Better to use the tensorflow for large dataset rathen than using it for small dataset. 



In [ ]:
# we need to have an inpput function  : 

result = linear_est.predict(eval_input_fn) # we need input function to preduict as well just like we need to train the model
print(result)

# to get the specific result we can take it as  : 
print(result[0]['probabilites'][1]) 

print(dfeval.loc[0])




We also can do the classification similar to we have done for the regression : 


classification   : diferentiating bwtween the classes and defining of they belong to a certain group.  


In [ ]:
CSV_COLUMN_NAMES = ['sepanlenght' , 'sepalwidth' , 'petallength' , 'petalwidth' , 'species']
SPECIES  = ['setosa' , 'versicolor' , 'virginia']

train_path = tf.keras.utils.get_file ('iris_training.csv' , "https://Next url")
test_path  = tf.keras.utils.get_file('test file name with the url ') 


train = pd.read_csv(train_path , names=CSV_COLUMN_NAMES , header=0)
test = pd.read_csv(test_path , names = CSV_COLUMN_NAMES , header = 0)



In [ ]:
train.head() # To check the data and get idea of how it works. 


Rest of the steps would be the same as other models do just we have to focus on the input function  : 
in here we dont have the epochs and the batch size is different



In [ ]:
def input_fn(features  , labels   ,training = True , batch_size = 256):
    # Converts the inputs to a dataset : 
    dataset = tf.data.Datset.from_tensor_slices((dict(features) , labels))
    if training :
        dataset = dataset.shuffle(1000).repeat()
    
    return dataset.batch(batch_size)


In [ ]:
# if there are all the numerical feature columns then we dont have to make the multiple for loops  : 
feature_columns  = []
for key in train.keys():
    feature_columns.append(tf.feature_column.numeric_column(key = key))



In [ ]:
# Building the model : for the classification model  :  same as the liner model we used it was pre built   :
# for ther are two type DNN classifier ( deep learnign classifier ) , LinearClassifier ( used for the most liner data ) usually deep learning classifier is used most of the time 

# Build DNN with 2 hidden layers with 20 and 10 hidden nodes each  

classifier   = tf.estimator.DNNClassifier(
    feature_columns=feature_columns,
    # two hidden layers fo 30 and 10 nodes in each node respectively  
    hidden_units=[30 , 10],
    # The model must choose between 3 classes 
    n_classes=3
)

In [ ]:
classifier.train(
    input_fn  = lambda :  input_fn(train , train_y , training  = True ),
    steps  = 5000 # simiilar to epoch but it has steps but the meaning it it goes to a dataset until it finds 5000 values or things like that

While running the train it finds the loss and prints it and over the period of time the losses should decrease and which means the model is learning but if the count is still high then we need to make somehting so that the losses are reduced. 

In [ ]:
classifier.evaluate(input_fn  = lambda : input_fn(test , test_y , training= False))
print(f"Accurary {**eval_result}")

